### ISSUE TITLE
Example in the Readme is wrong

### ISSUE THREAD

**Issue by quotschmacher** [RobertDaleSmith/SNESpad#1]
I think (due to some changes) the example in the main Reamde.md is wrong - the constructor there only takes 3 arguments. Whilst the constructor in the implementation takes 5 arguments with no default values.

**Comment by RobertDaleSmith** [comment]
Thanks for the heads up. Recently extended the project to use the SNES controller ports second data pin and the iobit pin. These pins are optional and can be set to unused pins values, -1, or 0xff.

I updated the example in the readme but all the examples in the examples folder should be up to date.

I will circle back in the next update and improve handling of these optional pins.
